version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'tg_user'
      POSTGRES_PASSWORD: 'tg_pwd'
