development:
#  adapter: async
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql
#  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: table_games_production
