default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: table_games_development

test:
  <<: *default
  database: table_games_test

production:
  <<: *default
  database: table_games_prod
